# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
        
    - name: Clean install dependencies and build
      run: npm ci
    
    - name: Run tests
      run: npm test

  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    
    - name: Clean install dependencies and build
      run: npm ci
    
    - name: Build database
      run: npm run db:sync
